#ifndef __LINUX_ATMEL_MXT_CONFIG
#define __LINUX_ATMEL_MXT_CONFIG

//#define CONFIG_MXT_DUMMY_CAL_AT_RESUME

#define CONFIG_MXT_PROBE_ALTERNATIVE_CHIP 2
//#define CONFIG_MXT_CAL_TRIGGER_T8_WITH_UNKONW_SOURCE
#define CONFIG_MXT_CAL_TRIGGER_CAL_WHEN_CFG_MATCH
//#define CONFIG_MXT_TRACK_TRUNK_DATA
//#define CONFIG_MXT_TRIGGER_PI_PRE_PROCESS_AT_FIRST_POWERUP
#define CONFIG_MXT_UPDATE_BY_OBJECT

//#if defined(CONFIG_MXT_PLUGIN_SUPPORT)
#define CONFIG_MXT_IRQ_WORKQUEUE
//#endif
#define CONFIG_MXT_I2C_DMA
//#define CONFIG_MXT_I2C_EXTFLAG
//#define CONFIG_MXT_PLUGIN_SUPPORT

//#undef CONFIG_OF
#if defined(CONFIG_FB)
//#undef CONFIG_FB
#endif

#endif
